export const siteConfig = {
  assets: {
    avatar: '/assets/images/avatar.png',
    discordGif: '/assets/gifs/discord.gif',
    logo: '/assets/images/logo.png',
    resume: '/assets/resume/Muhammad-Bilal-Resume-2025.pdf',
  },
  description: 'Software Engineer, cricket player based in Lahore, Pakistan.',
  keywords: [
    'Next.js',
    'TypeScript',
    'Tailwind CSS',
    'Vitest',
    'React Testing Library',
    'Framer Motion',
    'shadcn/ui',
    'Aceternity UI',
    'PUCIT',
    'Muhammad Bilal',
    'Muhammad Bilal Portfolio',
    'Muhammad Bilal Portfolio 2023',
    'Muhammad Bilal Portfolio 2024',
    'Muhammad Bilal Portfolio 2025',
    'Muhammad Bilal Portfolio 2026',
    'Muhammad Bilal Portfolio 2027',
    'Muhammad Bilal Portfolio 2028',
    'Muhammad Bilal Portfolio 2029',
    'Muhammad Bilal Portfolio 2030',
    'Muhammad Bilal Portfolio 2031',
    'Muhammad Bilal Portfolio 2032',
    'Muhammad Bilal Portfolio 2033',
    'Muhammad Bilal Portfolio 2034',
    'Muhammad Bilal Portfolio 2035',
    'Muhammad Bilal Portfolio 2036',
    'Muhammad Bilal Portfolio 2037',
    'Muhammad Bilal Portfolio 2038',
    'Muhammad Bilal Portfolio 2039',
    'Muhammad Bilal Portfolio 2040',
    'Muhammad Bilal Portfolio 2041',
    'Muhammad Bilal Nadeem Awan',
    'Muhammad Bilal Nadeem Awan Portfolio',
    'Muhammad Bilal Nadeem Awan Portfolio 2023',
    'Muhammad Bilal Nadeem Awan Portfolio 2024',
    'Muhammad Bilal Nadeem Awan Portfolio 2025',
    'Muhammad Bilal Nadeem Awan Portfolio 2026',
    'Muhammad Bilal Nadeem Awan Portfolio 2027',
    'Muhammad Bilal Nadeem Awan Portfolio 2028',
    'Muhammad Bilal Nadeem Awan Portfolio 2029',
    'Muhammad Bilal Nadeem Awan Portfolio 2030',
    'Muhammad Bilal Nadeem Awan Portfolio 2031',
    'Muhammad Bilal Nadeem Awan Portfolio 2032',
    'Muhammad Bilal Nadeem Awan Portfolio 2033',
    'Muhammad Bilal Nadeem Awan Portfolio 2034',
    'Muhammad Bilal Nadeem Awan Portfolio 2035',
    'Muhammad Bilal Nadeem Awan Portfolio 2036',
    'Muhammad Bilal Nadeem Awan Portfolio 2037',
    'Muhammad Bilal Nadeem Awan Portfolio 2038',
    'Muhammad Bilal Nadeem Awan Portfolio 2039',
    'Webflow Developer',
    'Webflow Extensions Developer',
    'Chrome Extension Developer',
    'Chrome Developer',
    'Bilal',
  ],
  links: {
    github: 'https://github.com/mb-awan',
    githubRepo: 'https://github.com/Muhammad-Bilal-official/portfolio1',
    githubRepositories: 'https://github.com/mb-awan?tab=repositories',
    linkedin: 'https://www.linkedin.com/in/muhammad-bilal-4299291b2/',
  },
  name: 'Muhammad Bilal',
  opImage: '/og-image.png',
  siteTitle: 'Muhammad Bilal',
  url: new URL('https://www.muhammad-bilal-nadeem-awan.com/'),
};

export type SiteConfig = typeof siteConfig;
